# Site settings
<<<<<<< HEAD
name: Jade Chen
location: 合肥
company: 安徽农业大学
position: 小白码农
github: https://github.com/
facebook: https://www.facebook.com/
phone: 1985560xxxx
email: love@cwjxbw1314.website

