# Site settings
title: Jade Chen 的 Github 博客
description: 主站博客（建设中）
baseurl: "" 
#change the baseurl to "https://cwjxbw1314.website/complete/" if you are using it as your user GitHub Pages
url: "https://cwjxbw1314.website/complete/"  


# GitHub User settings
username: Jade Chen
github_username: DAIMAhuoquzhe
user_description: 码农小白一个
user_title: 小白
email: love@cwjxbw1314.website 

# Blog Author settings
author: Jade Chen
  name: DAIMAhuoquzhe           
  picture:        
  email: love@cwjxbw1314.website          
  description: 。。。    
  twitter:
  facebook:
  github: https://github.com/DAIMAhuoquzhe/For-My-Darling-Jxbw         
  linkedin:
  clustrmap:      


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
